name: App CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build Image
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build frontend
        working-directory: ./client
        run: |
            npm install
            npm run build
            npm test
      - name: Build server
        working-directory: ./back-end
        run: |
            npm install
            pm2 stop "money-saver-app-server"
            pm2 start "money-saver-app-server"
            pm2 save
